import type {
  Company,
  Lead,
  Service,
  ServiceCategory,
  ChatThread,
  ChatMessage,
  NotificationItem,
  Plan,
  CreditPack,
  PurchaseHistoryItem,
  SupportTicket,
  FaqItem,
  Review,
  User,
} from '@/types';

export const mockCategories: ServiceCategory[] = [
  { id: 'architecture', name: 'Architecture', icon: 'business-outline', description: 'Designs, drawings, 3D plans', count: 412 },
  { id: 'structural', name: 'Structural Engineering', icon: 'construct-outline', description: 'Load, RCC, steel design', count: 287 },
  { id: 'legal', name: 'Legal Services', icon: 'briefcase-outline', description: 'Title, RERA, contracts', count: 154 },
  { id: 'approvals', name: 'Govt. Approvals', icon: 'shield-checkmark-outline', description: 'Sanction, NOC, RERA', count: 198 },
  { id: 'contractors', name: 'Contractors', icon: 'hammer-outline', description: 'Civil, finishing, MEP', count: 631 },
  { id: 'interior', name: 'Interior Design', icon: 'color-palette-outline', description: 'Turnkey interiors', count: 245 },
  { id: 'materials', name: 'Material Suppliers', icon: 'cube-outline', description: 'Cement, steel, tiles', count: 502 },
  { id: 'survey', name: 'Survey Services', icon: 'map-outline', description: 'Land, topo, drone', count: 87 },
  { id: 'project_mgmt', name: 'Project Management', icon: 'analytics-outline', description: 'PMC, supervision', count: 121 },
  { id: 'environmental', name: 'Environmental', icon: 'leaf-outline', description: 'EIA, clearances', count: 64 },
  { id: 'financial', name: 'Financial Services', icon: 'card-outline', description: 'Loans, valuation', count: 92 },
];

export const mockCompanies: Company[] = [
  {
    id: 'c1',
    ownerId: 'u2',
    name: 'Sthapati Architects',
    gst: '27ABCDE1234F1Z5',
    cin: 'U45200MH2014PTC123456',
    pan: 'ABCDE1234F',
    description: 'Award-winning residential & commercial architecture firm with 12+ years of pan-India delivery.',
    city: 'Mumbai',
    state: 'Maharashtra',
    yearFounded: 2012,
    employees: '20-50',
    rating: 4.7,
    reviewsCount: 128,
    certifications: ['COA Registered', 'IGBC Accredited', 'ISO 9001:2015'],
    team: [
      { id: 't1', name: 'Anjali Rao', role: 'Principal Architect' },
      { id: 't2', name: 'Vikram Shah', role: 'Senior Designer' },
      { id: 't3', name: 'Neha Iyer', role: 'BIM Lead' },
    ],
  },
  {
    id: 'c2',
    ownerId: 'u3',
    name: 'BuildRight Contractors',
    description: 'End-to-end civil contracting from foundation to finishing. Specialists in G+4 residential builds.',
    city: 'Bengaluru',
    state: 'Karnataka',
    yearFounded: 2008,
    employees: '50-200',
    rating: 4.5,
    reviewsCount: 312,
    certifications: ['CIDC Member', 'GST Registered'],
  },
  {
    id: 'c3',
    ownerId: 'u4',
    name: 'Sterling Materials Co.',
    description: 'OPC/PPC cement, TMT bars, vitrified tiles \u2014 bulk supply across South India.',
    city: 'Hyderabad',
    state: 'Telangana',
    yearFounded: 2003,
    employees: '200+',
    rating: 4.3,
    reviewsCount: 540,
  },
];

export const mockServices: Service[] = [
  {
    id: 's1',
    vendorId: 'c1',
    category: 'architecture',
    name: '3BHK Residential Architecture Package',
    description: 'Complete architectural design, structural drawings, 3D walkthrough, and BOQ for residential plots up to 2400 sqft.',
    priceFrom: 85000,
    priceUnit: 'per project',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: [],
    documents: [
      { id: 'd1', name: 'Sample-Floor-Plan.pdf', url: '#', sizeKb: 1240, premium: false },
      { id: 'd2', name: 'Material-Specs.pdf', url: '#', sizeKb: 480, premium: true },
    ],
    rating: 4.8,
    reviewsCount: 64,
    experienceYears: 12,
    featured: true,
    premium: true,
    deliverables: ['Floor Plans', '3D Elevations', 'Working Drawings', 'BOQ', 'Site Visits'],
    tags: ['Vastu', 'Modern', 'Sustainable'],
  },
  {
    id: 's2',
    vendorId: 'c2',
    category: 'contractors',
    name: 'Civil Construction \u2014 G+1 Turnkey',
    description: 'Per sqft turnkey civil construction including structure, brickwork, plastering, plumbing & electrical rough-in.',
    priceFrom: 1850,
    priceUnit: 'per sqft',
    city: 'Bengaluru',
    state: 'Karnataka',
    images: [],
    documents: [{ id: 'd3', name: 'Sample-Contract.pdf', url: '#', sizeKb: 320, premium: false }],
    rating: 4.5,
    reviewsCount: 122,
    experienceYears: 16,
    featured: true,
    premium: false,
    deliverables: ['Structural Work', 'Brickwork', 'Plastering', 'Waterproofing'],
    tags: ['Turnkey', 'Residential'],
  },
  {
    id: 's3',
    vendorId: 'c3',
    category: 'materials',
    name: 'OPC 53 Grade Cement \u2014 Bulk Supply',
    description: 'OPC 53 grade premium cement, MOQ 100 bags, delivered to site within 48 hours across South India.',
    priceFrom: 395,
    priceUnit: 'per bag',
    city: 'Hyderabad',
    state: 'Telangana',
    images: [],
    documents: [],
    rating: 4.3,
    reviewsCount: 88,
    experienceYears: 21,
    featured: false,
    premium: false,
    deliverables: ['Free Delivery', 'GST Invoice', 'Quality Certificate'],
    tags: ['Bulk', 'OPC', 'IS269'],
  },
  {
    id: 's4',
    vendorId: 'c1',
    category: 'interior',
    name: 'Modular Kitchen Design & Install',
    description: 'Custom modular kitchens with HDHMR carcass, soft-close hardware, and 10-year warranty.',
    priceFrom: 1350,
    priceUnit: 'per sqft',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: [],
    documents: [],
    rating: 4.6,
    reviewsCount: 41,
    experienceYears: 9,
    featured: false,
    premium: true,
    deliverables: ['Design Consultation', 'HDHMR Modules', 'Installation', 'Warranty'],
    tags: ['Modular', 'Kitchen'],
  },
  {
    id: 's5',
    vendorId: 'c2',
    category: 'project_mgmt',
    name: 'PMC \u2014 Project Management Consultancy',
    description: 'End-to-end project supervision, vendor coordination, cost control & quality audits.',
    priceFrom: 250000,
    priceUnit: 'per project',
    city: 'Bengaluru',
    state: 'Karnataka',
    images: [],
    documents: [],
    rating: 4.7,
    reviewsCount: 27,
    experienceYears: 14,
    featured: true,
    premium: true,
    deliverables: ['Weekly Reports', 'Vendor Mgmt', 'Cost Control', 'QA/QC Audits'],
    tags: ['PMC', 'Supervision'],
  },
];

export const mockReviews: Review[] = [
  { id: 'r1', authorName: 'Rohit Mehta', rating: 5, comment: 'Excellent design, delivered on time. Highly recommend.', createdAt: new Date(Date.now() - 86400000).toISOString() },
  { id: 'r2', authorName: 'Priya Sharma', rating: 4, comment: 'Good communication, minor delays in final drawings.', createdAt: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: 'r3', authorName: 'Aakash Verma', rating: 5, comment: 'Vastu compliant and beautiful elevations. Worth it.', createdAt: new Date(Date.now() - 86400000 * 14).toISOString() },
];

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    buyerName: 'Suresh Patil',
    buyerMobile: '+91 98xxxxxx10',
    buyerEmail: 'suresh@example.com',
    serviceId: 's1',
    serviceName: '3BHK Residential Architecture Package',
    message: 'Need architectural design for 2200 sqft plot in Pune. Budget around 1L. Vastu mandatory.',
    budget: 100000,
    city: 'Pune',
    status: 'new',
    createdAt: new Date(Date.now() - 3600_000).toISOString(),
    updatedAt: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: 'l2',
    buyerName: 'Reena Nair',
    buyerMobile: '+91 98xxxxxx22',
    serviceId: 's2',
    serviceName: 'Civil Construction \u2014 G+1 Turnkey',
    message: 'Construction of a duplex in Whitefield. ~2800 sqft total. Looking for quotation.',
    budget: 5500000,
    city: 'Bengaluru',
    status: 'contacted',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3600_000 * 4).toISOString(),
  },
  {
    id: 'l3',
    buyerName: 'Mohammed Iqbal',
    buyerMobile: '+91 98xxxxxx33',
    serviceId: 's5',
    serviceName: 'PMC \u2014 Project Management Consultancy',
    message: 'Need PMC for a 15-month commercial build, 32k sqft.',
    budget: 800000,
    city: 'Hyderabad',
    status: 'negotiation',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const mockChatThreads: ChatThread[] = [
  {
    id: 'ch1',
    participantName: 'Sthapati Architects',
    lastMessage: 'We can schedule a site visit on Saturday at 11 AM.',
    lastMessageAt: new Date(Date.now() - 3600_000 * 2).toISOString(),
    unreadCount: 2,
    serviceId: 's1',
  },
  {
    id: 'ch2',
    participantName: 'BuildRight Contractors',
    lastMessage: 'Sharing revised quotation in 30 mins.',
    lastMessageAt: new Date(Date.now() - 86400000).toISOString(),
    unreadCount: 0,
  },
  {
    id: 'ch3',
    participantName: 'Sterling Materials',
    lastMessage: 'Bulk price for 500 bags?',
    lastMessageAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    unreadCount: 1,
  },
];

export const mockChatMessages: Record<string, ChatMessage[]> = {
  ch1: [
    { id: 'm1', threadId: 'ch1', fromMe: false, text: 'Hi! Thanks for your enquiry about the 3BHK package.', createdAt: new Date(Date.now() - 3600_000 * 6).toISOString() },
    { id: 'm2', threadId: 'ch1', fromMe: true, text: 'Hi, what is the timeline for full set of drawings?', createdAt: new Date(Date.now() - 3600_000 * 5).toISOString() },
    { id: 'm3', threadId: 'ch1', fromMe: false, text: 'Typically 4 weeks from sign-off. We can schedule a site visit on Saturday at 11 AM.', createdAt: new Date(Date.now() - 3600_000 * 2).toISOString() },
  ],
};

export const mockNotifications: NotificationItem[] = [
  { id: 'n1', type: 'lead', title: 'New lead received', body: 'Suresh Patil enquired about your 3BHK package.', createdAt: new Date(Date.now() - 3600_000).toISOString(), read: false },
  { id: 'n2', type: 'payment', title: 'Payment successful', body: '\u20B9499 credit pack purchased.', createdAt: new Date(Date.now() - 86400000).toISOString(), read: false },
  { id: 'n3', type: 'subscription', title: 'Plan upgraded', body: 'You are now on Commercial Pro.', createdAt: new Date(Date.now() - 86400000 * 4).toISOString(), read: true },
  { id: 'n4', type: 'system', title: 'New service approved', body: 'Your listing "Modular Kitchen" is now live.', createdAt: new Date(Date.now() - 86400000 * 7).toISOString(), read: true },
];

export const mockPlans: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    pricePerMonth: 0,
    credits: 50,
    features: ['Browse services', 'View basic info', '50 starter credits'],
  },
  {
    id: 'premium',
    name: 'Premium',
    pricePerMonth: 499,
    credits: 500,
    highlight: 'Best for individuals',
    recommended: true,
    features: ['500 monthly credits', 'Unlock premium listings', 'Document downloads', 'Priority support'],
  },
  {
    id: 'commercial_pro',
    name: 'Commercial Pro',
    pricePerMonth: 2499,
    credits: 2500,
    highlight: 'For vendors & agencies',
    features: ['Unlimited listings', 'Featured positioning', 'Advanced analytics', 'Dedicated account manager', 'Team seats (5)'],
  },
];

export const mockCreditPacks: CreditPack[] = [
  { id: 'cp1', credits: 100, price: 199 },
  { id: 'cp2', credits: 500, price: 799, bonus: 50 },
  { id: 'cp3', credits: 1500, price: 1999, bonus: 250 },
  { id: 'cp4', credits: 5000, price: 5999, bonus: 1000 },
];

export const mockPurchaseHistory: PurchaseHistoryItem[] = [
  { id: 'ph1', date: new Date(Date.now() - 86400000 * 2).toISOString(), description: 'Credit pack \u2014 500 credits', amount: 799, type: 'credits', status: 'success' },
  { id: 'ph2', date: new Date(Date.now() - 86400000 * 14).toISOString(), description: 'Premium plan \u2014 monthly', amount: 499, type: 'plan', status: 'success' },
  { id: 'ph3', date: new Date(Date.now() - 86400000 * 28).toISOString(), description: 'Featured listing boost', amount: 299, type: 'featured', status: 'success' },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 't1',
    subject: 'Unable to download premium document',
    status: 'in_progress',
    category: 'Payments & Credits',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3600_000 * 2).toISOString(),
    messages: [
      { id: 'tm1', fromMe: true, text: 'My credits were deducted but download failed.', createdAt: new Date(Date.now() - 86400000).toISOString() },
      { id: 'tm2', fromMe: false, text: 'Our team is investigating, will refund credits if needed.', createdAt: new Date(Date.now() - 3600_000 * 2).toISOString() },
    ],
  },
  {
    id: 't2',
    subject: 'Vendor not responding',
    status: 'open',
    category: 'Vendor Issues',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    messages: [{ id: 'tm3', fromMe: true, text: 'Vendor has not responded for 3 days.', createdAt: new Date(Date.now() - 86400000 * 3).toISOString() }],
  },
];

export const mockFaqs: FaqItem[] = [
  { id: 'f1', question: 'How do credits work?', answer: 'Credits unlock vendor contacts, downloads, and premium listings. Each action has a fixed cost.', category: 'Credits' },
  { id: 'f2', question: 'How do I get verified as a vendor?', answer: 'Complete KYC under Profile > KYC and submit GST/CIN documents for admin review.', category: 'Vendors' },
  { id: 'f3', question: 'Is my payment secure?', answer: 'All payments are processed via Razorpay/Stripe with PCI-DSS compliance.', category: 'Payments' },
  { id: 'f4', question: 'Can I refund unused credits?', answer: 'Credits are non-refundable but never expire on paid plans.', category: 'Credits' },
];

export const mockUser: User = {
  id: 'u1',
  name: 'Demo User',
  email: 'demo@contractindia.in',
  mobile: '+91 9000000000',
  role: 'individual',
  city: 'Pune',
  state: 'Maharashtra',
  credits: 120,
  plan: 'premium',
  kycStatus: 'verified',
  createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
};
